### ISSUE TITLE
Sending text back fails on occasion

### ISSUE THREAD

**Issue by Jake-Moss** [tecosaur/emacs-everywhere#18]
Running Doom emacs using the `everywhere` module on native-comp-pgtk 

Emacs-everywhere fails to send text on occasion to a variety of applications including

- FireFox
- Discord
- Thunderbird
- Alacritty

```
Debugger entered--Lisp error: (error "Unknown \"nil\" back-end: Aborting export")
  error("Unknown \"%s\" back-end: Aborting export" nil)
  org-export-barf-if-invalid-backend(nil)
  #<subr org-export-as>(md nil nil nil nil)
  apply(#<subr org-export-as> (md nil nil nil nil))
  (let ((old-async-init-file org-export-async-init-file) (org-export-async-init-file (make-temp-file "doom-org-async-export"))) (let ((temp-file org-export-async-init-file) (temp-buffer (generate-new-buffer " *temp file*" t))) (unwind-protect (prog1 (save-current-buffer (set-buffer temp-buffer) (prin1 (list 'progn (list ... ... ... ... ...) (cons ... ...) (list ... org-export-async-init-file)) (current-buffer))) (save-current-buffer (set-buffer temp-buffer) (write-region nil nil temp-file nil 0))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))) (apply orig-fn args))
  +org--fix-async-export-a(#<subr org-export-as> md nil nil nil nil)
  apply(+org--fix-async-export-a #<subr org-export-as> (md nil nil nil nil))
  org-export-as(md nil nil nil nil)
  org-export-to-buffer(md #<buffer emacs-everywhere-F7cb7N>)
  emacs-everywhere-return-converted-org-to-gfm()
  emacs-everywhere-finish()
  emacs-everywhere-finish-or-ctrl-c-ctrl-c()
  #<subr funcall-interactively>(emacs-everywhere-finish-or-ctrl-c-ctrl-c)
  apply(#<subr funcall-interactively> emacs-everywhere-finish-or-ctrl-c-ctrl-c)
  funcall-interactively(emacs-everywhere-finish-or-ctrl-c-ctrl-c)
  #<subr call-interactively>(emacs-everywhere-finish-or-ctrl-c-ctrl-c nil nil)
  apply(#<subr call-interactively> (emacs-everywhere-finish-or-ctrl-c-ctrl-c nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> emacs-everywhere-finish-or-ctrl-c-ctrl-c nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (emacs-everywhere-finish-or-ctrl-c-ctrl-c nil nil))
  call-interactively(emacs-everywhere-finish-or-ctrl-c-ctrl-c nil nil)
  command-execute(emacs-everywhere-finish-or-ctrl-c-ctrl-c)
```
This specific backtrace occurred when sending to discord.

I am running xmonad with xfce on Arch lts

**Comment by tecosaur** [comment]
I run Emacs 28 (HEAD) with native-comp and pgtk on KDE, and I didn't have any issues like you described.

I'm guessing this is either xmonad/xfce specific. The error you show looks rather odd though, I'm guessing you're able to export Org buffers as markdown without issue normally?

**Comment by Jake-Moss** [comment]
I am able to export to markdown using `org-md-export-to-markdown` fine.
I've also tried with and without the markdown module enabled, no change

**Comment by tecosaur** [comment]
The definition of `emacs-everywhere-return-converted-org-to-gfm` is:
https://github.com/tecosaur/emacs-everywhere/blob/99997af93310128cc95b8ddceacb448daed2403a/emacs-everywhere.el#L435-L442

So I'd try opening an Emacs Everywhere instance and running `(org-export-to-buffer 'md (current-buffer))` and see what happens.

**Comment by Jake-Moss** [comment]
Its working now? I can't seem to get it to fail. Something very strange is happening. If I don't run into this again for a reasonable amount of time I'll close this. Otherwise when it starts to fail again Ill update you

**Comment by tecosaur** [comment]
Sounds good to me :+1:

**Comment by corrafig** [comment]
I found this everywhere mode as it was added to Doom. Sounds useful but I have multiple reliability/compatibility issues. I didn't create a new bug yet because I just started to use this. However, I have following issues (without errors in Emacs).

**Kate**
Text import to Emacs doesn't work if text is selected with Ctrl + a in kate. Emacs opens an empty buffer and new text overwrites existing data in kate (C-c C-c).

**Mousepad**
Text selection does not stay in Mousepad and C-c C-c in Emacs adds text to cursor point instead of replaces existing text.

At least the latter one sounds Mousepad issue. Not necessary a bug but just incompatibility with this mode. I really like idea of this mode but I'm too afraid to use it to write longer text in Emacs if I'm afraid of losing text/work (without manually adding to kill ring before submit).

**Comment by tecosaur** [comment]
Thanks for commenting. I've found this to be pretty good, but if other people are able to work out where and how it's falling short we should be able to make it more reliable.

I just tested Kate and it seems that selecting text does not set the system's primary selection. This is a bit dodgy, but I don't think there's anything I can do about it.

With regards to being afraid of losing text you write, that was something I didn't want to happen to me either.
That's why whether or not the copying back to the original source works as I hope, the content is copied to the clipboard.

**Comment by orlandini** [comment]
I am facing the same issue on ubuntu. Any tips on debugging it?

```
Debugger entered--Lisp error: (error "Unknown \"nil\" back-end: Aborting export")
  signal(error ("Unknown \"nil\" back-end: Aborting export"))
  error("Unknown \"%s\" back-end: Aborting export" nil)
  org-export-barf-if-invalid-backend(nil)
  org-export-as(md nil nil nil nil)
  org-export-to-buffer(md #<buffer emacs-everywhere-uXBLxB>)
  emacs-everywhere-return-converted-org-to-gfm()
  run-hooks(emacs-everywhere-final-hooks)
  emacs-everywhere-finish()
  emacs-everywhere-finish-or-ctrl-c-ctrl-c()
  funcall-interactively(emacs-everywhere-finish-or-ctrl-c-ctrl-c)
  call-interactively(emacs-everywhere-finish-or-ctrl-c-ctrl-c nil nil)
  command-execute(emacs-everywhere-finish-or-ctrl-c-ctrl-c)

**Comment by malb** [comment]
I ran into the same problem, turns out the `md` backend wasn't enabled
by default, so I did:
```emacs-lisp
    (use-package org
      :custom ((org-export-backends '(md odt latex icalendar html ascii))))
```

**Comment by tecosaur** [comment]
The situation should be better as of 9e24e4e8e81ac93c9e13748759a15436ea565966.

**Comment by tecosaur** [comment]
Please re-open if this is still an issue.
